version: "3"

services:
  zookeeper:
    container_name: "zookeeper"
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
      
  kafka:
    container_name: "kafka"
    image: 'wurstmeister/kafka:latest'
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_ADVERTISED_HOST_NAME: instance-1.southamerica-east1-a.c.sincere-bongo-264115.internal
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://instance-1.southamerica-east1-a.c.sincere-bongo-264115.internal:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "tableA:1:1"
    depends_on:
        - zookeeper

  mysql-db:
    container_name: "mysql-db"
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '12345'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '12345'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-db:/var/lib/mysql
  
  # Names our volume
volumes:
  mysql-db: