version: "3"

services:
  zookeeper:
    container_name: "zookeeper"
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
      
  kafka:
    container_name: "kafka"
    image: 'wurstmeister/kafka:latest'
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_ADVERTISED_HOST_NAME: instance-1.southamerica-east1-a.c.sincere-bongo-264115.internal
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://instance-1.southamerica-east1-a.c.sincere-bongo-264115.internal:9094
      KAFKA_LISTENERS: INSIDE://kafka:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      # KAFKA_CREATE_TOPICS: "my_connect_configs:1:1,my_connect_offsets:1:1,my_connect_statuses:1:1"
    depends_on:
        - zookeeper

    
  debezium-connector:
    container_name: "debezium-connector"
    image: "debezium/connect:1.1"
    ports:
      - '8083:8083'
    links:
      - kafka
      - zookeeper
      - mysql-db:mysql
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses

  mysql-db:
    container_name: "mysql-db"
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '12345'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '12345'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-db:/var/lib/mysql
    command: --log-bin=mysql-bin.log --server-id=1
    # docker run -it --rm mysql:5.7 --verbose --help
  
  # Names our volume
volumes:
  mysql-db: